= Lab Guide: Introducing supply chain security with ansible-sign
:doctype: book
:experimental:
:notoc:
:toc-title: Table of Contents
:nosectnums:
:icons: font

_Learn how to sign content by using ansible-sign and apply supply-chain security measures, a major Dev Tools capability._

---

== Lab Briefing

`ansible-sign`: Utility for signing and verifying Ansible project directory contents.

Project signing and verification lets you sign files in your project directory, then verify whether or not that content has changed in any way, or files have been added or removed from the project unexpectedly. To do this, you require a private key for signing and a matching public key for verifying.

== Lab Guide: Hands-On Tasks

**The Workflow for Signing AAP Projects:**

* Sign your project directory containing playbooks, rulebooks, roles, etc.
* Sync the signed project to AAP's Project Sync
* AAP verifies the signature before execution
* Only validated, trusted content runs

Using ansible-sign together with the Automation Hub collection signing feature allows to secure the supply chain end-to-end from content development to production.

NOTE: In this lab we will only cover the workstation side of the content signing. You can apply what you learned here to verify content on your own AAP instance later.

=== Task 1: Create a GPG key 

To use `ansible-sign` your workstation needs to have a GPG key available to cryptographically sign the content. Although it exceeds the scope of this workshop, we will create one quickly to show the end to end steps.

.  *Install pinentry-curses, a dependency for gpg*:
+
[source,bash,role=execute]
----
 sudo dnf install pinentry-curses -y
----

. *Create a gpg.txt file with the following content:*
+
[source,bash,role=execute]
----
cat >~/gpg.txt <<EOF
%echo Generating a basic OpenPGP key
Key-Type: default
Key-Length: 4096
Subkey-Type: default
Subkey-Length: default
Name-Real: workshop
Name-Comment: with no passphrase
Name-Email: student@localhost
Expire-Date: 0
%no-ask-passphrase
%no-protection
# Do a commit here, so that we can later print "done" :-)
%commit
%echo done
EOF
----


.  *Generate the gpg key:*
+
[source,bash,role=execute]
----
gpg --batch --gen-key ~/gpg.txt
----

. *Verify the key is created:*
+
[source,bash,role=execute]
----
gpg --list-secret-keys
----

=== Task 2: Supply-chain security: Signing your Ansible collection 

This task demonstrates how to cryptographically sign an Ansible Project using `ansible-sign`. We will be using `myansibleproject` and our `mycowsay.yml` playbook.

---

=== Task 3: Set the environment

. *Make sure you are in the `myansibleproject` directory:*
+
[source,bash,role=execute]
----
cd /home/rhel/myansibleproject
----

. *Switch `ade` to standard mode:* Before we can sign our packages, we need to disable editable mode to remove the recursive symlinks. 
+
[source,bash,role=execute]
----
ade install /home/rhel/myansibleproject/collections/ansible_collections/mynamespace/mycollection
----


=== Task 2: Create a MANIFEST.in File

. *In VS Code, create a new file called `MANIFEST.in`* in the root of your project. Add the following content to it. We will be excluding a couple of directories and signing a REAME and playbook. This is only meant as an example, your needs might vary:
+
[source,bash,role=execute]
----
# Exclude .venv FIRST before any includes
global-exclude .venv
global-exclude .venv/*
prune .venv

# Exclude .git
global-exclude .git
global-exclude .git/*
prune .git

# Now include what you want to sign
include README.md
include mycowsay.yml
----

NOTE: Internally, ansible-sign makes use of the distlib.manifest module of Python’s distlib library, and thus MANIFEST.in must follow the syntax that this library specifies. Check the Python Packaging User Guide for an explanation of the MANIFEST.in file directives.

=== Task 3: Sign the Project with ansible-sign

. *Now we can sign the files listed in the `MANIFEST.in`:* The way that ansible-sign protects content from tampering is by taking checksums (sha256) of all of the secured files in the project, compiling those into a checksum manifest file, and then finally signing that manifest file.
+
[source,bash,role=execute]
----
ansible-sign project gpg-sign .
----
+
The output of the command above should look like this:
+
[source,bash]
----
[OK   ] GPG signing successful!
[NOTE ] Checksum manifest: ./.ansible-sign/sha256sum.txt
[NOTE ] GPG summary: signature created
----

=== Task 4: Verifying the content with ansible-sign


. *Confirm the files in MANIFEST.in got checksums:*
+
[source,bash,role=execute]
----
cat .ansible-sign/sha256sum.txt
----

. *Verify your signed files have the correct checksum:*
+
[source,bash,role=execute]
----
ansible-sign project gpg-verify .
----

. *Switch `ade` back to editable mode:*
+
[source,bash,role=execute]
----
ade install --editable /home/rhel/myansibleproject/collections/ansible_collections/mynamespace/mycollection
----

=== Task 5: Enabling verification in our AAP executions

. *We won't cover this here, but the next steps would be:*
.. Create a credential with our GPG Public Key
.. Push our project to a git repository
.. Create a project in AAP to pull from that repository and assign our GPG credential
.. AAP will verify the content of the project at every sync


---
== Next Steps

You have successfully signed and verified your playbook, this ensured that it can't be tampered with and continue to run unnoticed. Please click the **Next** button below to proceed to the next module.